version: '2'
services:
  jenkins:
    build: .
    # restart: unless-stopped
    image: reangd/alpine-proxy:latest
    network_mode: "bridge"
    environment:
      - S6_LOGGING=0
      - CERT_EMAIL="admin@example.com"
      - CERT_DOMAIN="example.com"
      # - CONSUL_IP="1.2.3.4"
      # - CONSUL_PORT="8500"
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      # - ./log:/var/log:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - /etc/localtime:/etc/localtime:ro