version: '2'
services:
  tor:
    build:
    restart: unless-stopped
    network_mode: "bridge"
    container_name: tor
    hostname: tor
    image: reangd/alpine-tor:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=0
      - SERVICE_CRON=0
    ports:
      - "9050:9050"
    volumes:
      # - ./log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
