version: '2'
services:
  jenkins:
    build: .
    restart: unless-stopped
    network_mode: "bridge"
    container_name: nginx
    image: reangd/alpine-nginx:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=0
      #
      # nginx params:
      #
      # - NGINX_OPTIONS=...
    ports:
      - "80:80"      # HTTP
      # - "443:443"    # HTTPS
    volumes:
      # - ./log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
