version: '2'
services:
  base:
    build: .
    restart: unless-stopped
    image: reangd/alpine-base:latest
    container_name: alpine-base
    environment:
      - S6_LOGGING=0
      # - SERVICE_CRON=1
      # - RESTORE_NAME="daily.1"
    volumes:
      # - ./log:/var/log:rw
      # - ./backup:/backup:rw
      # - ./data:/data:rw
      - /etc/localtime:/etc/localtime:ro
